apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: load-generator
  name: load-generator
  namespace: zad1
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while sleep 0.000000000000001; do wget -q -O- http://php-apache; done
    stdin: true
    tty: true
    image: busybox:1.28
    name: load-generator
    resources:
      limits:
        memory: 250Mi
        cpu: 250m
      requests:
        memory: 150Mi
        cpu: 150m 
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
