apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: zad1 # dodanie namespace
spec:
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources: # dodanie zasobów
          limits:
            memory: 250Mi
            cpu: 250m
          requests:
            memory: 150Mi
            cpu: 150m 
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    run: php-apache
  namespace: zad1 # dodanie namespace
spec:
  ports:
  - port: 80
  selector:
    run: php-apache